### PR TITLE
Fix arm ik

### PR DESCRIPTION
**Pull request by furushchev**
use `std::vector<KDL::JntArray>` instead of `KDL::JntArray` as output variable `jnt_pos_out`, and use first solution, since old function is deleted on package `pr2_arm_kinematics`.

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
I'll check if this compiles tomorrow. 

Edit: it must also pass builds on the build server.

**Comment by furushchev** [comment]
ping

**Comment by UltronDestroyer** [comment]
Can you PR to the hydro-devel-unstable branch with only the fix commit?

**Comment by UltronDestroyer** [comment]
ping

**Comment by garaemon** [comment]
ping @furushchev

**Comment by furushchev** [comment]
sorry for late response. I sent PR.

**Comment by furushchev** [comment]
I think it is good to close.

**Comment by furushchev** [comment]
ping

**Comment by UltronDestroyer** [comment]
Can you rename catkin.cmake to CMakeLists.txt?

Alternatively, if this PR is catkinizing this package, does it compile afterwards?

**Comment by UltronDestroyer** [comment]
Edit @furushchev nevermind. The catkinization has been done in the hydro-devel-unstable branch by myself 5 months ago. Can you make the changes to arm_ik.cpp and PR to that branch? I'll merge it down into hydro-devel after that.

**Comment by furushchev** [comment]
@TheDash You already merged my PR ( I sent as [another PR](https://github.com/PR2/pr2_common_actions/pull/31/files).). So I just close this PR. 
BTW, it seems that you ends most of your catkinization with lack or wrong of install command that is necessary for catkin install and may cause fatal error on building/running PR2 related packages. I think it's better to write test code, and please consider to use travis to decide if you could merge all PRs.

**Comment by UltronDestroyer** [comment]
Sorry, I opened the wrong ticket from the ping.

**Pull request closed without merging**
